#!/bin/bash
if
  [ "$1" == "" ]
then
  echo usage: startit <inputdir>
  exit 4
fi
TESTDATADIR=$1
ROOT=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
DATADIR=$ROOT/data
INTRAY=$DATADIR/intray
PROCTRAY=$DATADIR/temptray
OUTTRAY=$DATADIR/outtray
mkdir -f -p $INTRAY
mkdir -f -p $OUTTRAY
mkdir -f -p $TEMPTRAY
cp $TESTDATADIR/* $INTRAY/
echo start runit
./runit
