#!/bin/bash
if
  [ "$1" == "" ]
then
  echo 'usage: startit inputdir'
  exit 4
fi
TESTDATADIR=$1
ROOT=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
DATADIR=$ROOT/data
INTRAY=$DATADIR/intray
PROCTRAY=$DATADIR/proctray
OUTTRAY=$DATADIR/outtray
mkdir -p $INTRAY
mkdir -p $OUTTRAY
mkdir -p $PROCTRAY
cp $TESTDATADIR/* $INTRAY/
echo start runit
./runit
